apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    k8s-app: flannel
data:
  net-conf.json: |
    {
      "Network": "${pod_cidr}",
      "Backend": {
        "Type": "vxlan"
      }
    }
