apiVersion: v1
kind: Service
metadata:
  name: calico-metrics
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  # service is created to allow prometheus to scrape endpoints
  clusterIP: None
  selector:
    k8s-app: calico-node
  ports:
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
