---
apiVersion: v1
data:
  ca.crt: ${helm_ca_cert}
  tls.crt: ${tiller_cert} 
  tls.key: ${tiller_key}
kind: Secret
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-secret
  namespace: kube-system
type: Opaque
