apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
    spec:
      serviceAccountName: kube-router
      containers:
        - name: kube-router
          image: ${kube_router_image}
          imagePullPolicy: IfNotPresent
          args:
            - --run-router=true
            - --run-firewall=true
            - --run-service-proxy=true
            - --kubeconfig=/etc/kubernetes/kubeconfig
            - --bgp-graceful-restart
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            httpGet:
              path: /healthz
              port: 20244
            initialDelaySeconds: 10
            periodSeconds: 3
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: cni-conf-dir
              mountPath: /etc/cni/net.d
            - name: kubeconfig
              mountPath: /etc/kubernetes/kubeconfig
              readOnly: true
      initContainers:
        - name: install-cni
          image: busybox
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - set -e -x;
              if [ ! -f /etc/cni/net.d/10-kuberouter.conf ]; then
                TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
                cp /etc/kube-router/cni-conf.json $${TMP};
                mv $${TMP} /etc/cni/net.d/10-kuberouter.conf;
              fi;
              CNI_VERSION=v0.7.1;
              wget -O- https://github.com/containernetworking/plugins/releases/download/$CNI_VERSION/cni-plugins-amd64-$CNI_VERSION.tgz | tar xz -C /opt/cni/bin
          volumeMounts:
            - name: cni-conf-dir
              mountPath: /etc/cni/net.d
            - name: cni-bin-dir
              mountPath: /opt/cni/bin
            - name: kube-router-cfg
              mountPath: /etc/kube-router
      hostNetwork: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: cni-conf-dir
          hostPath:
            path: /etc/kubernetes/cni/net.d
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: kube-router-cfg
          configMap:
            name: kube-router-cfg
        - name: kubeconfig
          hostPath:
            path: /etc/kubernetes/kubeconfig
