---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-vip-configmap
  namespace: kube-system
data:
  ${apiserver_vip}: default/kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-vip-configmap-startup-script
  namespace: kube-system
data:
  startup-script: |
    #! /bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    RULE=(POSTROUTING -m ipvs --ipvs --vdir ORIGINAL --vmethod MASQ -j MASQUERADE)

    iptables -t nat -C "$${RULE[@]}" 2>/dev/null || iptables -t nat -A "$${RULE[@]}"
