---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-apiserver-vip
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-apiserver-vip
spec:
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: kube-apiserver-vip
  template:
    metadata:
      labels:
        tier: control-plane
        k8s-app: kube-apiserver-vip
      annotations:
        checkpointer.alpha.coreos.com/checkpoint: "true"
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      hostNetwork: true
      serviceAccountName: kube-apiserver-vip
      priorityClassName: system-cluster-critical
      containers:
        - name: kube-keepalived-vip
          image: ${keepalived_vip_image}
          imagePullPolicy: Always
          args:
            - "--run-only"
            - process
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /dev
              name: dev
            - mountPath: /usr/local/etc/keepalived/keepalived.conf
              name: config
              subPath: keepalived.conf
            - mountPath: /check-apiserver.sh
              name: config
              subPath: check-apiserver.sh
            - mountPath: /check-health.sh
              name: config
              subPath: check-health.sh
            - mountPath: /keepalived-state.sh
              name: config
              subPath: keepalived-state.sh
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            exec:
              command:
                - /check-health.sh
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: config
          configMap:
            name: kube-apiserver-vip-configmap
            items:
              - key: keepalived.conf
                path: keepalived.conf
                mode: 0444
              - key: check-apiserver.sh
                path: check-apiserver.sh
                mode: 0555
              - key: check-health.sh
                path: check-health.sh
                mode: 0555
              - key: keepalived-state.sh
                path: keepalived-state.sh
                mode: 0555
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
